from django.db import models

# Create your models here.


class StudentAdmssion(models.Model):
    Name_Bangla = models.CharField(max_length=100)
    blood_group = models.CharField(max_length=100)
    name_English = models.CharField(max_length=100)
    Religion = models.CharField(max_length=100)
    Date_Of_Birth = models.CharField(max_length=100)
    Nationality = models.CharField(max_length=100)
    Gender = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='studentimage/')
    Mobile = models.CharField(max_length=100)
    Present_Address = models.TextField()
    Email = models.CharField(max_length=100)
    Parmanant_Address = models.CharField(max_length=100)
    Father_Name =models.CharField(max_length=100)
    Mother_Name  =models.CharField(max_length=100)
    Father_Phone =models.CharField(max_length=100)
    Mother_Phone =models.CharField(max_length=100)
    Father_NID =models.IntegerField()
    Father_NID =models.IntegerField()
    Father_Profession =models.CharField(max_length=100)
    Mother_Profession=models.CharField(max_length=100)
    Father_Designation=models.CharField(max_length=100)
    Mother_Designation=models.CharField(max_length=100)
    motherOffice_Name_Addres=models.CharField(max_length=100)
    motherOffice_Name_Addres=models.CharField(max_length=100)
    Father_Office_Contact_No=models.CharField(max_length=100)
    Mother_Office_Contact_No=models.CharField(max_length=100)
    Father_Photo=models.ImageField(upload_to='fatherimage/')
    Mother_Photo=models.ImageField(upload_to='motherimage/')
    Guardian_Receiver =models.CharField(max_length=100)
    Guardian_Name =models.CharField(max_length=100)
    Relation_With_Student =models.CharField(max_length=100)
    Guardian_Phone =  models.CharField(max_length=100)
    Status = models.CharField(max_length=100)
    Guardian_Profession = models.CharField(max_length=100)
    Guardian_Designation = models.CharField(max_length=100)
    Office_Contact_No = models.CharField(max_length=100)
    Office_Name_Address = models.TextField(max_length=100)